server:
  port: ${port:8080}

logging:
  level:
    org.springframework.web: WARN
    com.hiring.test: INFO

spring:
  application:
    name: Back-End
  datasource:
    url: jdbc:h2:mem:testDB;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    initialize: true
    driver-class-name: org.h2.Driver
    continue-on-error: false
    platform: h2
  jpa:
    show-sql: false
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
  error:
    whitelabel.enabled: true
  h2:
    console:
      enabled: true
      path: /h2/console
